env:
  global:
  - PACKAGE_NAME=deb-builder-bintray
  - BINTRAY_REPO_NAME=debian
  - BINTRAY_LICENSE=LGPL-2.1

before_install:
- export RELEASE_VERSION=$(cat VERSION)
- export BUILD_VERSION=$RELEASE_VERSION.$(date "+%Y%m%d").$TRAVIS_BUILD_NUMBER
- export PACKAGE_NAME_VERSION=$PACKAGE_NAME-$BUILD_VERSION.deb

script:
- dpkg-deb --build $PACKAGE_NAME
- mv $PACKAGE_NAME.deb $PACKAGE_NAME_VERSION

after_success:
- ls -l $PACKAGE_NAME_VERSION
- md5sum $PACKAGE_NAME_VERSION
- dpkg --contents $PACKAGE_NAME_VERSION

before_deploy:
  - sed -i "s/__NAME__/$PACKAGE_NAME/g" bintray-descriptor.json
  - sed -i "s/__REPO_NAME__/$BINTRAY_REPO_NAME/g" bintray-descriptor.json
  - sed -i "s/__SUBJECT__/$BINTRAY_USER/g" bintray-descriptor.json
  - sed -i "s/__LICENSE__/$BINTRAY_LICENSE/g" bintray-descriptor.json
  - sed -i "s/__VERSION__/$BUILD_VERSION/g" bintray-descriptor.json

deploy:
  provider: bintray
  file: bintray-descriptor.json
  user: $BINTRAY_USER
  key: $BINTRAY_API_KEY
  skip_cleanup: true
